[phases.setup]
nixPkgs = ["tesseract", "tesseract-ocr-jpn"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "streamlit run complete_streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
