[phases.setup]
aptPkgs = [
    "tesseract-ocr", 
    "tesseract-ocr-jpn", 
    "libgl1-mesa-dev", 
    "libglib2.0-0", 
    "libsm6", 
    "libxext6", 
    "libxrender-dev", 
    "libgomp1",
    "libglib2.0-dev",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libgdk-pixbuf-xlib-2.0-dev",
    "libffi-dev",
    "shared-mime-info"
]

[start]
cmd = "python test_start.py"
